services:
  db:
    image: postgres
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: netskope@123
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - nts
  
  redis:
    image: redis:latest
    container_name: task-broker
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nts
  
  sla_engine:
    image: nts
    command: celery -A sla_engine.tasks worker -B --loglevel=info
    links:
      - redis
    depends_on:
      - redis
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      SLACK_WEB_HOOK: ${SLACK_WEB_HOOK}
    volumes:
      - ./nts:/nts
    networks:
      - nts
    
  app:
    image: nts
    build:
      context: ./nts
      dockerfile: Dockerfile
    links:
      - db
    volumes:
      - ./nts:/nts
    depends_on:
     - db
     - redis
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    ports:
      - "8000:8000"
    networks:
      - nts
  
volumes:
  postgres:
  redis_data:

networks:
  nts:
    driver: bridge
