# SLA Targets per priority across customer tiers
---
CASB:
  P0: 
    response: 10
    resolution: 60
  P1: 
    response: 15
    resolution: 240
  P2: 
    response: 30
    resolution: 360
SWG:
  P0:
    response: 10 
    resolution: 60
  P1:
    response: 30 
    resolution: 240
  P2:
    response: 45
    resolution: 360
ZTNA:
  P0: 
    response: 10
    resolution: 60
  P1: 
    response: 15
    resolution: 120
  P2: 
    response: 30
    resolution: 240